stages:
  - test

pytest:
  stage: test
  only:
    - merge_requests
  image: 
    name: continuumio/miniconda3:latest
  before_script:
    - conda create --name bestprot -y python=3.9
    - conda install -n bestprot -c conda-forge -c bioconda mmseqs2
    - conda run -n bestprot python -m pip install torch --extra-index-url https://download.pytorch.org/whl/cpu
    - conda run -n bestprot python -m pip install -e .
    - conda run -n bestprot python -m pip install pytest
    - conda run -n bestprot python -m pip install awscli
  script:
    - conda run -n bestprot python -m pytest .

