stages:
  - test
  - build

pytest:
  stage: test
  only:
    - merge_requests
  image: 
    name: continuumio/miniconda3:latest
  before_script:
    - conda create --name proteinflow -y python=3.9
    - conda install -n proteinflow -c conda-forge -c bioconda mmseqs2
    - conda run -n proteinflow python -m pip install torch --extra-index-url https://download.pytorch.org/whl/cpu
    - conda run -n proteinflow python -m pip install -e .
    - conda run -n proteinflow python -m pip install pytest
  script:
    - conda run -n proteinflow python -m pytest .

update_docs:
  stage: build
  image: 
    name: python:3.9
  before_script:
    - python -m pip install -e .
    - python -m pip install pdoc3
  script:
    - git config user.email "liza@adaptyvbio.com"
    - git config user.name "Liza Kozlova"
    - git remote add gitlab_origin https://oauth2:$ACCESS_TOKEN@gitlab.com/adaptyvbio/bestprot.git
    - . make_docs.sh
    - echo "" >> html_docs/proteinflow/index.html
    - echo '<!--'"$(date) -->" >> html_docs/proteinflow/index.html
    - git add .
    - git commit -m "push back from pipeline"
    - git push gitlab_origin HEAD:main -o ci.skip # prevent triggering pipeline again
