stages:
  - test
  - deploy

pytest:
  stage: test
  only:
    - merge_requests
  image: 
    name: continuumio/miniconda3:latest
  before_script:
    - conda create --name bestprot -y python=3.9
    - conda install -n bestprot -c conda-forge -c bioconda mmseqs2
    - conda run -n bestprot python -m pip install torch --extra-index-url https://download.pytorch.org/whl/cpu
    - conda run -n bestprot python -m pip install -e .
    - conda run -n bestprot python -m pip install pytest
    - conda run -n bestprot python -m pip install awscli
  script:
    - conda run -n bestprot python -m pytest .

push-back-to-remote:
  stage: deploy
  before_script:
    - python -m pip install -e .
    - python -m pip install pdoc
  script:
    - git config user.email "my-email@email.com"
    - git config user.name "ci-bot"
    - git remote add gitlab_origin https://oauth2:$ACCESS_TOKEN@gitlab.com/path-to-project.git
    - git add .
    - git commit -m "push back from pipeline"
    - git push gitlab_origin HEAD:main -o ci.skip # prevent triggering pipeline again
