stages:
  - test

pytest:
  stage: test
  # only:
  #   - merge_requests
  image: 
    name: continuumio/miniconda3:latest
  before_script:
    - conda create --name bestprot -y python=3.9.15
    - source activate bestprot
    - conda install -c conda-forge -c bioconda mmseqs2
    - python -m pip install torch --extra-index-url https://download.pytorch.org/whl/cpu
    - python --version
    - python -m pip install -e .
    - python -m pip install pytest
  script:
    - python -m pytest .
