repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
-   repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        args: ["--fail-under=70"]
-   repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        additional_dependencies:
          - toml
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: flake8
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.6.0
    hooks:
      - id: pyupgrade
        args: [--py36-plus]
-   repo: https://github.com/crate-ci/typos
    rev: v1.15.0
    hooks:
      - id: typos
        args: ["--config", "_typos.toml", "-w"]
