repos:
-   repo: https://github.com/ambv/black
    rev: 23.7.0
    hooks:
      - id: black
-   repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        args: ["--fail-under=50", "-v"]
-   repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        additional_dependencies:
          - toml
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: flake8
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.9.0
    hooks:
      - id: pyupgrade
        args: [--py36-plus]
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
    -   id: codespell
        name: codespell
        description: Checks for common misspellings in text files.
        entry: codespell -L ser,unx,conect --skip "*ipynb,*/constants.py"
        language: python
        types: [text]
# -   repo: https://github.com/jshwi/docsig
#     rev: v0.30.0
#     hooks:
#       - id: docsig
#         args:
#           - "--check-class"
#           - "--check-dunders"
#           - "--check-overridden"
#           - "--check-protected"
#           - "--ignore-no-params"
#           - "--summary"
