repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
# -   repo: local
#     hooks:
#     - id: pdoc
#       name: pdoc
#       language: system
#       entry: python -m pip install pdoc3 