{% set version = "2.4.1" %}
package:
  name: "proteinflow"
  version: {{ version }}

source:
  git_url: https://github.com/adaptyvbio/ProteinFlow.git
  git_rev: v{{ version }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - proteinflow = proteinflow.scripts.proteinflow_cli:cli

requirements:
  host:
    - python
    - setuptools
    - pip
    - wheel
  build:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - numpy>=1.21,<1.25
    - editdistance>=0.6.0
    - Biopython==1.79 
    - click>=8.1.3
    - biopandas>=0.4.1
    - boto3=
    - p-tqdm
    - networkx==2.8.8
    - einops
    - pandas
    - pytorch>=1.10.0
    - biotite==0.35.0
    - aiobotocore
    - awscli
    - bs4
    - rcsbsearch
    - mmseqs2
    - foldseek
    - pyyaml
    - rdkit
    - pypdb
    - joblib

about:
  home: https://github.com/adaptyvbio/ProteinFlow
  license: BSD-3-Clause
  license_familY: BSD
  license_file: LICENSE
  summary: "Versatile pipeline for processing protein structure data for deep learning applications."
  doc_url: "https://adaptyvbio.github.io/ProteinFlow/"
  dev_url: "https://github.com/adaptyvbio/ProteinFlow"
