name: Update image on Docker Hub

on: push

jobs:
  update_docker:
    runs-on: ubuntu-latest
    name: Build and push Docker image + update README
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: adaptyvbio
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build and push Docker image
        run: |
          docker build -t adaptyvbio/proteinflow:$GITHUB_REF_NAME .
          docker image push adaptyvbio/proteinflow:$GITHUB_REF_NAME
      - name: Push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: adaptyvbio
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        with:
          destination_container_repo: adaptyvbio/proteinflow
          provider: dockerhub
          short_description: 'Versatile pipeline for processing protein structure data for deep learning applications.'
          readme_file: 'README.md'