name: Run pytest

on:
  pull_request:
    branches: [ main ]

env:
  MY_REF: ${{ format('refs/heads/{0}', github.event.pull_request.head.ref) }}
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["3.8", "3.9", "3.10"]

    steps:
      - name: Check if relevant files have changed
        uses: actions/github-script@0.9.0
        id: service-changed
        with:
          result-encoding: string
          script: |
            const result = await github.pulls.listFiles({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.number,
              per_page: 100
            })
            const serviceChanged = result.data.filter(f => f.filename.startsWith("proteinflow/")).length > 0
            console.log(serviceChanged)
            return serviceChanged
      - uses: actions/checkout@v3
        if: ${{ steps.service-changed.outputs.result == 'true' }}
        with:
            ref: ${{ env.MY_REF}}
            fetch-depth: 0
      - name: Install dependencies
        if: ${{ steps.service-changed.outputs.result == 'true' }}
        run: |
          conda update conda -y
          conda create --name proteinflow -y python=${{ matrix.version }}
          conda install -n proteinflow -c conda-forge -c bioconda mmseqs2
          conda run -n proteinflow python -m pip install torch --extra-index-url https://download.pytorch.org/whl/cpu
          conda run -n proteinflow python -m pip install awscli pytest flake8
          conda run -n proteinflow python -m pip install numpy
          conda run -n proteinflow python -m pip install "rcsbsearch @ git+https://github.com/sbliven/rcsbsearch@dbdfe3880cc88b0ce57163987db613d579400c8e"
          conda run -n proteinflow python -m pip install -e .

      - name: Lint with flake8
        if: ${{ steps.service-changed.outputs.result == 'true' }}
        run: |
          # stop the build if there are Python syntax errors or undefined names
          conda run -n proteinflow flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          conda run -n proteinflow flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        if: ${{ steps.service-changed.outputs.result == 'true' }}
        run: |
          conda run -n proteinflow pytest tests
