name: Test and update docs

on:
  pull_request:
    branches: [ main ]

env:
  MY_REF: ${{ format('refs/heads/{0}', github.event.pull_request.head.ref) }}

jobs:
  test_and_update:

    runs-on: ubuntu-latest
    permissions: 
      contents: write

    steps:
    - name: Check if relevant files have changed
      uses: actions/github-script@0.9.0
      id: service-changed
      with:
        result-encoding: string
        script: |
          const result = await github.pulls.listFiles({
            owner: context.payload.repository.owner.login,
            repo: context.payload.repository.name,
            pull_number: context.payload.number,
            per_page: 100
          })
          const serviceChanged = result.data.filter(f => f.filename.startsWith("proteinflow/")).length > 0
          console.log(serviceChanged)
          return serviceChanged
      - uses: actions/checkout@v3
        if: ${{ steps.service-changed.outputs.result == 'true' }}
        with:
            ref: ${{ env.MY_REF}}
            fetch-depth: 0
      - name: Set up Python
        if: ${{ steps.service-changed.outputs.result == 'true' }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        if: ${{ steps.service-changed.outputs.result == 'true' }}
        run: |
          conda create --name proteinflow -y python=3.9
          conda install -n proteinflow -c conda-forge -c bioconda mmseqs2
          conda run -n proteinflow python -m pip install torch --extra-index-url https://download.pytorch.org/whl/cpu
          conda run -n proteinflow python -m pip install awscli pytest flake8
          conda run -n proteinflow python -m pip install "rcsbsearch @ git+https://github.com/sbliven/rcsbsearch@dbdfe3880cc88b0ce57163987db613d579400c8e"
          conda run -n proteinflow python -m pip install -e .

      - name: Lint with flake8
        if: ${{ steps.service-changed.outputs.result == 'true' }}
        run: |
          # stop the build if there are Python syntax errors or undefined names
          conda run -n proteinflow flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          conda run -n proteinflow flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        if: ${{ steps.service-changed.outputs.result == 'true' }}
        run: |
          conda run -n proteinflow pytest tests
      - name: Install pdoc3 and black
        if: ${{ steps.service-changed.outputs.result == 'true' }}
        run: |
          conda run -n proteinflow python -m pip install pdoc3 black
      - name: Reformat the code
        if: ${{ steps.service-changed.outputs.result == 'true' }}
        run: |
          conda run -n proteinflow black .
      - name: Update the docs
        if: ${{ steps.service-changed.outputs.result == 'true' }}
        run: |
          git pull
          conda run -n proteinflow pdoc3 -o docs --html --force proteinflow 
          mv docs/proteinflow/* docs/
          rm -r docs/proteinflow
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ steps.service-changed.outputs.result == 'true' }}
        with:
          commit_message: auto update
          skip_checkout: true
    
