name: Run pytest

on:
  pull_request:
    branches: [ main ]

env:
  MY_REF: ${{ format('refs/heads/{0}', github.event.pull_request.head.ref) }}
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
        if: ${{ !startsWith(github.event.head_commit.message, 'auto update') }}
        with:
            ref: ${{ env.MY_REF}}
            fetch-depth: 0
      - name: Get Commit Message
        run: |
          MSG=$(git log --format=%B -n 1 ${{github.event.after}})
          echo "::set-env name=COMMIT_MESSAGE::${MSG}"
      - name: Echo commit message
        run: |
          echo "Commit SHA: ${{github.event.after}}, commit message: ${{env.COMMIT_MESSAGE}} (or ${COMMIT_MESSAGE})"
      - name: Install dependencies
        if: ${{ env.COMMIT_MESSAGE != 'auto update' }}
        run: |
          conda update conda -y
          conda create --name proteinflow -y python=${{ matrix.version }}
          conda install -n proteinflow -c conda-forge -c bioconda mmseqs2
          conda run -n proteinflow python -m pip install torch --extra-index-url https://download.pytorch.org/whl/cpu
          conda run -n proteinflow python -m pip install awscli pytest flake8
          conda run -n proteinflow python -m pip install numpy
          conda run -n proteinflow python -m pip install "rcsbsearch @ git+https://github.com/sbliven/rcsbsearch@dbdfe3880cc88b0ce57163987db613d579400c8e"
          conda run -n proteinflow python -m pip install -e .

      - name: Lint with flake8
        if: ${{ env.COMMIT_MESSAGE != 'auto update' }}
        run: |
          # stop the build if there are Python syntax errors or undefined names
          conda run -n proteinflow flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          conda run -n proteinflow flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        if: ${{ env.COMMIT_MESSAGE != 'auto update' }}
        run: |
          conda run -n proteinflow pytest tests
