# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  update:
    name: Update docs
    runs-on: ubuntu-latest
    permissions: 
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
            token: ${{ secrets.PAT }}
            ref: main
      - name: Install dependencies
        run: |
          conda create --name proteinflow -y python=3.9
          conda run -n proteinflow python -m pip install torch --extra-index-url https://download.pytorch.org/whl/cpu
          conda run -n proteinflow python -m pip install numpy
          conda run -n proteinflow python -m pip install -e .
      - name: Install pdoc3 and black
        run: |
          conda run -n proteinflow python -m pip install pdoc3 black
      - name: Reformat the code
        run: |
          conda run -n proteinflow black .
      - name: Update the docs
        run: |
          git pull origin main
          conda run -n proteinflow . dev/make_docs.sh
          echo ${{ needs.test.outputs.update }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: auto update
          skip_checkout: true
