name: Update docs

on:
  push:
    branches: [ main ]

jobs: 
  update_docs:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install -e .
          python -m pip install pdoc3
      - name: Update the docs
        run: |
          . make_docs.sh
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update docs
    
