name: Update docs

on:
  push:
    branches: [ main ]

jobs:
  update:
    runs-on: ubuntu-latest
    permissions: 
      contents: write

    steps:
      - name: Check if relevant files have changed
        uses: actions/github-script@0.9.0
        id: service-changed
        with:
          result-encoding: string
          script: |
            const result = await github.pulls.listFiles({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.number,
              per_page: 100
            })
            const serviceChanged = result.data.filter(f => f.filename.startsWith("proteinflow/")).length > 0
            console.log(serviceChanged)
            return serviceChanged
      - uses: actions/checkout@v3
        if: ${{ steps.service-changed.outputs.result == 'true' }}
        with:
            fetch-depth: 0
            token: ${{ secrets.PAT }}
      - name: Install dependencies
        if: ${{ steps.service-changed.outputs.result == 'true' }}
        run: |
          conda create --name proteinflow -y python=3.9
          conda run -n proteinflow python -m pip install torch --extra-index-url https://download.pytorch.org/whl/cpu
          conda run -n proteinflow python -m pip install numpy
          conda run -n proteinflow python -m pip install -e .
      - name: Install pdoc3 and black
        if: ${{ steps.service-changed.outputs.result == 'true' }}
        run: |
          conda run -n proteinflow python -m pip install pdoc3 black
      - name: Reformat the code
        if: ${{ steps.service-changed.outputs.result == 'true' }}
        run: |
          conda run -n proteinflow black .
      - name: Update the docs
        if: ${{ steps.service-changed.outputs.result == 'true' }}
        run: |
          git pull
          conda run -n proteinflow . make_docs.sh
          echo ${{ needs.test.outputs.update }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ steps.service-changed.outputs.result == 'true' }}
        with:
          commit_message: auto update
          skip_checkout: true
